//
// Module Lab1_lib.Power2.flow
//
// Created:
//          by - amitnag.UNKNOWN (SHOHAM)
//          at - 14:39:08 11/30/2020
//
// Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
//

`resetall
`timescale 1ns/10ps
module Power2( 
   // Port Declarations
   input   wire    [9:0]  Mu,   // mu between 0-1000 milli (0-1)
   output  reg     [9:0]  pow   // return answer for 2^(-((Mu-0.5)^2)), in milli!!
);


// Internal Declarations



/////////////////////////////////////////////////////////////////
// Flowchart process0
always @ (Mu)
begin : process0_flowchart_proc
   if ( Mu < 125) begin
       pow <= 875;
   end
   else if (Mu < 250) begin
       pow <= 934;
   end
   else if (Mu < 375) begin
       pow <= 975;
   end
   else if (Mu < 625) begin
       pow <=997;
   end
   else if (Mu < 750) begin
       pow <= 975;
   end
   else if (Mu < 875) begin
       pow <= 934;
   end
   else
   begin
       pow <= 875;
   end
end

endmodule // Power2

